server:
  port: 7001
eureka:
  instance:
    hostname: www.eureka-7001.com
  client:
    fetch-registry: false #是否注册到eureka
    register-with-eureka: false #是否从服务器获取注册信息
    service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/